// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8wrQ5GMCWnaIDagNNo3XDCTXUOB1UPQ',
    appId: '1:282987386919:web:e34fb132238afaaa739602',
    messagingSenderId: '282987386919',
    projectId: 'tugas-akhir-37a95',
    authDomain: 'tugas-akhir-37a95.firebaseapp.com',
    storageBucket: 'tugas-akhir-37a95.firebasestorage.app',
    measurementId: 'G-3MTWGS462B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeANtx07HpjAXY0r7WJbZrwve8y1DKc8c',
    appId: '1:282987386919:android:657db8f429b97b49739602',
    messagingSenderId: '282987386919',
    projectId: 'tugas-akhir-37a95',
    storageBucket: 'tugas-akhir-37a95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBockMrZve84OYpR8M0lg3eIdUj2npP6Uw',
    appId: '1:282987386919:ios:55747a04ceb6e85c739602',
    messagingSenderId: '282987386919',
    projectId: 'tugas-akhir-37a95',
    storageBucket: 'tugas-akhir-37a95.firebasestorage.app',
    androidClientId: '282987386919-muqccd6ga6vk0gppk6r1h6u9koaulkes.apps.googleusercontent.com',
    iosClientId: '282987386919-q0blu5affmn7552v0718pkpvjcv29p19.apps.googleusercontent.com',
    iosBundleId: 'com.example.kohood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBockMrZve84OYpR8M0lg3eIdUj2npP6Uw',
    appId: '1:282987386919:ios:55747a04ceb6e85c739602',
    messagingSenderId: '282987386919',
    projectId: 'tugas-akhir-37a95',
    storageBucket: 'tugas-akhir-37a95.firebasestorage.app',
    androidClientId: '282987386919-muqccd6ga6vk0gppk6r1h6u9koaulkes.apps.googleusercontent.com',
    iosClientId: '282987386919-q0blu5affmn7552v0718pkpvjcv29p19.apps.googleusercontent.com',
    iosBundleId: 'com.example.kohood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx8wrQ5GMCWnaIDagNNo3XDCTXUOB1UPQ',
    appId: '1:282987386919:web:8477d8444e2e2990739602',
    messagingSenderId: '282987386919',
    projectId: 'tugas-akhir-37a95',
    authDomain: 'tugas-akhir-37a95.firebaseapp.com',
    storageBucket: 'tugas-akhir-37a95.firebasestorage.app',
    measurementId: 'G-GKYCTCXE2M',
  );
}
